#TODO will be used in the 'Composing images' section of the Hands-on Lab

version: '3'

services:
  mysql: #How to configure this image: https://hub.docker.com/_/mysql
    image: mysql:5.7.27
    volumes:
      - ./quotes:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - backend

# commented out to make it more production like...
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.7
#    ports:
#      - "8888:80"
#    links:
#      - mysql
#    environment:
#      - MYSQL_USERNAME=root
#      - MYSQL_ROOT_PASSWORD=secret
#      - PMA_HOST=mysql
#    depends_on:
#      - mysql
#    networks:
#      - backend

  quote-service:
    image: back-end
    ports:
      - "8080:8080"
#      - "4848:4848"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    ports:
      - "3000:3000"
    links:
      - quote-service
    depends_on:
      - quote-service
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mysql-data:
    driver: local
