#TODO will be used in the 'Composing images' section of the Hands-on Lab

version: '3'

services:
  db:
    image: mariadb:10.7.3
    volumes:
      - ./quotes:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "8888:80"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - backend

  quote-service:
    image: ivonet/back-end
    command: java -jar /opt/app.jar --spring.profiles.active=docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - frontend
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    ports:
      - "3000:3000"
    depends_on:
      - quote-service
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mariadb-data:
    driver: local
