#TODO will be used in the 'Composing images' section of the Hands-on Lab

version: '3'

services:
# TODO add the db service

# TODO add the phpmyadmin service

# TODO add quote-service

# TODO add web-service

networks:
  frontend:
  backend:

volumes:
  mariadb-data:
    driver: local
