#TODO will be used in the 'Composing images' section of the Hands-on Lab

version: '3'

services:
  mariadb: #How to configure this image: https://hub.docker.com/_/mariadb
    image: mariadb:10.7.3
    volumes:
      - ./quotes:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - backend

  quote-service:
    image: back-end
    ports:
      - "8080:8080"
      - "4848:4848"
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    ports:
      - "3000:3000"
    links:
      - quote-service
    depends_on:
      - quote-service
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mariadb-data:
    driver: local
