version: '3'

services:
  mysql: #How to configure this image: https://hub.docker.com/_/mysql
    image: mysql:5.7.27
    volumes:
      - ./quotes:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend

# TODO add quote-service

# TODO add web-service

networks:
  backend:

volumes:
  mysql-data:
    driver: local
