#TODO will be used in the 'Composing images' section of the Hands-on Lab

version: '3'

services:
  db:
    image: mariadb:10.7.3
    volumes:
      - ./quotes:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    networks:
      - backend

# TODO add quote-service

# TODO add web-service

networks:
  frontend:
  backend:

volumes:
  mariadb-data:
    driver: local
